//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arduino_simple_16x16_Dot_Matrix_code_generator_DEMO.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arduino_simple_16x16_Dot_Matrix_code_generator_DEMO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   
        ///byte Display_Buffer[ Display_Num_Word * 2 ],
        ///     Display_Swap_Buffer[ Display_Num_Word ][ 32 ];
        ///bool Shift_Bit = 0;            // SPI detail config
        ///unsigned int Shift_Count = 0,  // Count var is must be 0
        ///             Display_Word_Count = 0;
        ///byte Message_index = 0;
        ///byte temp = 0x80;
        ///
        ///bool enable_virtual = true;
        ///void setup(){
        ///    //가상 장치 지원 기능을 비활성화 하고 싶다면
        ///    //bool enable_virtual = true;을
        ///    //bool enable_virtual = false;로 변경해 주십시오.
        ///    if(enable_virtual)
        ///        Serial.begin(1000000);
        /// [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #include &lt;Arduino.h&gt;
        ///#include &lt;avr/pgmspace.h&gt;
        ///#include &lt;SPI.h&gt;
        ///
        /////Shift register pin value (By using SPI communication)
        /////쉬프트(74HC595N) 레지스터를 SPI 통신으로 제어할때 필요한 핀 번호 입니다.
        ///const byte STCP_PIN = 7,  // Latch(Storage)상태 1: 쓰기, 0: 적용
        ///           DS_PIN   = 11, // Data In: CLK 주기에 맞춰 데이터 전송
        ///           SHCP_PIN = 13; // CLK: 데이터 동기화를 위한 Clock 신호
        ///
        ///#define LEDARRAY_D 2 //CD4511 디코더 DIN핀: 4bit(0~15)의 4번째 비트
        ///#define LEDARRAY_C 3 //CD4511 디코더 CIN핀: 4bit(0~15)의 3번째 비트
        ///#define LEDARRAY_B 4 //CD4511 디코더 BIN핀: [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
    }
}
